- hosts: nginx
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - nginx
  vars:
    nginx_user: www-data

- hosts: dbservers
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - mysql

- hosts: wordpress
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - wordpress
